"""Database module for PostgreSQL operations."""

from .connection import get_connection, get_cursor, close_connection
from .transactions import transactional, TransactionContext
from .repositories import (
    upsert_amc,
    upsert_scheme,
    upsert_period,
    upsert_company,
    upsert_company_master,
    get_isin_details,
    get_canonical_sector,
    create_snapshot,
    insert_holdings,
    check_snapshot_exists,
    record_extraction_run,
    check_file_already_extracted,
    delete_extraction_run_and_holdings,
    upsert_isin_master,
    get_isin_master_details,
    find_entity_by_name,
    find_entity_by_symbol,
    fuzzy_search_entity,
    create_corporate_entity,
    log_resolution_audit,
    get_previous_period_id,
    check_period_locked,
    upsert_nav_entries,
    find_potential_scheme_renames,
    record_pending_merge,
    record_notification,
)

__all__ = [
    "get_connection",
    "get_cursor",
    "close_connection",
    "transactional",
    "TransactionContext",
    "upsert_amc",
    "upsert_scheme",
    "upsert_period",
    "upsert_company",
    "upsert_company_master",
    "get_isin_details",
    "get_canonical_sector",
    "create_snapshot",
    "insert_holdings",
    "check_snapshot_exists",
    "record_extraction_run",
    "check_file_already_extracted",
    "delete_extraction_run_and_holdings",
    "upsert_isin_master",
    "check_period_locked",
    "upsert_nav_entries",
    "find_potential_scheme_renames",
    "record_pending_merge",
    "record_notification",
]
