# Canonical AMC Names
AMC_HDFC = "HDFC MUTUAL FUND"
AMC_SBI = "SBI MUTUAL FUND"
AMC_KOTAK = "KOTAK MAHINDRA MUTUAL FUND"
AMC_ICICI = "ICICI PRUDENTIAL MUTUAL FUND"
AMC_HSBC = "HSBC MUTUAL FUND"
AMC_NIPPON = "NIPPON INDIA MUTUAL FUND"
AMC_AXIS = "AXIS MUTUAL FUND"
AMC_ABSL = "ADITYA BIRLA SUN LIFE MUTUAL FUND"
AMC_ANGELONE = "ANGEL ONE MUTUAL FUND"
AMC_UTI = "UTI MUTUAL FUND"
AMC_MIRAE = "MIRAE ASSET MUTUAL FUND"
AMC_PPFAS = "PARAG PARIKH MUTUAL FUND"
AMC_BAJAJ = "BAJAJ FINSERV MUTUAL FUND"
AMC_WEALTH = "THE WEALTH COMPANY MUTUAL FUND"

# Mapping of short codes (slugs) to canonical names
AMC_MAPPING = {
    "hdfc": AMC_HDFC,
    "sbi": AMC_SBI,
    "icici_pru": AMC_ICICI,
    "std_icici_pru": AMC_ICICI,
    "icici": AMC_ICICI,
    "hsbc": AMC_HSBC,
    "kotak": AMC_KOTAK,
    "nippon": AMC_NIPPON,
    "axis": AMC_AXIS,
    "absl": AMC_ABSL,
    "uti": AMC_UTI,
    "mirae_asset": AMC_MIRAE,
    "ppfas": AMC_PPFAS,
    "bajaj": AMC_BAJAJ,
    "angelone": AMC_ANGELONE,
    "wealth_company": AMC_WEALTH
}
